export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_METEORITES_PENDING = 'REQUEST_METEORITES_PENDING';
export const REQUEST_METEORITES_SUCCESS = 'REQUEST_METEORITES_SUCCESS';
export const REQUEST_METEORITES_FAILED = 'REQUEST_METEORITES_FAILED';
